### ISSUE TITLE
De profundis

### ISSUE THREAD

**Issue by julieemelyncumming** [ELVIS-Project/Dodecachordon-Data-Set#2]
https://github.com/ELVIS-Project/Dodecachordon-Data-Set/blob/master/Book-III/Literature-Examples/Champion-Jos1511_De-profundis.pdf

Could we make the two partes of this motet into two different files?  As Glarean describes it, it changes from Dorian to Phrygian.

**Comment by musicus** [comment]
Note: This is an issue with all multi-part pieces originating from the [Josquin Project](http://josquin.stanford.edu).

**Comment by musicus** [comment]
I've split _De profundis_ into its two parts (Part 1, Part 2), and added the resulting four files (two music .xml, and two .pdf) into the https://github.com/ELVIS-Project/Dodecachordon-Data-Set/tree/master/Book-III/Literature-Examples directory.
