### ISSUE TITLE
Qui mihi ministrat

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/Dodecachordon-Data-Set#3]
Is that the Ionian example of _Qui mihi_ from p. 261 & p. 419, or is that the Lydian example from p. 261 & p. 416?

**Comment by imlorenz** [comment]
Hi Reiner,

I transcribed the version from the top of pg. 262, so I think it is different from the polyphonic example on 419. The chapter the example is in emphasizes the Lydian mode.  The example doesn’t contain a flat in the signature.  For Glarean, I think it would contain the diezeugmenon tetrachord, which would make it a version of the “true” Lydian.  Let me know if you have any other questions.

Ian

On Feb 11, 2016, at 6:33 PM, Reiner Krämer <notifications@github.com<mailto:notifications@github.com>> wrote:

Is that the Ionian example of Qui mihi from p. 261 & p. 419, or is that the Lydian example from p. 261 & p. 416?

**Comment by musicus** [comment]
Perhaps I should have been more clear: my question was not about mode. Just follow the file naming convention when uploading a file.

:notes: :bowtie:

**Comment by musicus** [comment]
I went ahead and re-named [the files](https://github.com/ELVIS-Project/Dodecachordon-Data-Set/tree/master/Book-III/Literature-Examples) according to the naming convention:
- Book-3_Qui-mihi_p-262.pdf
- Book-3_Qui-mihi_p-262.xml

**Comment by imlorenz** [comment]
Oh I’m sorry.  That was my fault for misreading your question.  My apologies.  Thanks for renaming the file!

All the best,

Ian
On Feb 12, 2016, at 7:51 AM, Reiner Krämer <notifications@github.com<mailto:notifications@github.com>> wrote:

Perhaps I should have been more clear: my question was not about mode. Just follow the file naming convention when uploading a file :-).
