### ISSUE TITLE
Should we post MuseScore files too?

### ISSUE THREAD

**Issue by NinaPenner** [ELVIS-Project/Dodecachordon-Data-Set#4]
I estimate consuming my remaining hours within the next week or two. Since someone else will be correcting my stuff, perhaps it makes sense for us to post MuseScore files to the repository as well. Otherwise I will need to give someone these files so that they can be easily edited. It seems to me that the best way to do corrections is for the corrector to simply edit the MuseScore files and then re-Export them into XML and PDF.

**Comment by musicus** [comment]
:+1:  Sounds Good!

**Comment by julieemelyncumming** [comment]
I agree!  Julie

Julie E. Cumming
Schulich School of Music, McGill University
